---
name: module_14/product
properties:
- name: address
  type: string
- name: category_array
  type: array
- name: enabled
  type: boolean
- name: expiry_date
  type: integer
- name: location
  type: geojson
- name: meta_desc
  type: string
- name: meta_title
  type: string
- name: module_field_14/product/inventory/1
  type: integer
- name: module_field_14/product/inventory/2
  type: string
- name: module_field_14/product/inventory/3
  type: string
- name: module_field_14/product/price/aud/1
  type: float
- name: module_field_14/product/price/aud/2
  type: float
- name: module_field_14/product/price/aud/3
  type: string
- name: module_field_14/product/price/aud/4
  type: array
- name: module_field_14/product/price/cad/1
  type: float
- name: module_field_14/product/price/cad/2
  type: float
- name: module_field_14/product/price/cad/3
  type: string
- name: module_field_14/product/price/cad/4
  type: array
- name: module_field_14/product/price/eur/1
  type: float
- name: module_field_14/product/price/eur/2
  type: float
- name: module_field_14/product/price/eur/3
  type: string
- name: module_field_14/product/price/eur/4
  type: array
- name: module_field_14/product/price/gbp/1
  type: float
- name: module_field_14/product/price/gbp/2
  type: float
- name: module_field_14/product/price/gbp/3
  type: string
- name: module_field_14/product/price/gbp/4
  type: array
- name: module_field_14/product/price/nzd/1
  type: float
- name: module_field_14/product/price/nzd/2
  type: float
- name: module_field_14/product/price/nzd/3
  type: string
- name: module_field_14/product/price/nzd/4
  type: array
- name: module_field_14/product/price/usd/1
  type: float
- name: module_field_14/product/price/usd/2
  type: float
- name: module_field_14/product/price/usd/3
  type: string
- name: module_field_14/product/price/usd/4
  type: array
- name: module_field_14/product_1
  type: string
- name: module_field_14/product_2
  type: string
- name: module_field_14/product_3
  type: array
- name: module_field_14/product_4
  type: string
- name: module_field_14/product_5
  type: string
- name: module_field_14/product_6
  type: boolean
- name: module_field_14/product_7
  type: string
- name: name
  type: string
- name: og_desc
  type: string
- name: og_image
  type: string
- name: og_title
  type: string
- name: og_type
  type: string
- name: og_url
  type: string
- name: release_date
  type: integer
- name: secure_zone_array
  type: array
- name: slug
  type: string
- name: twitter_type
  type: string
- name: weighting
  type: integer
---
